name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # concurrency:
    #   group: Sonarcloud
    strategy:
      matrix:
        include:
          - dir: auth-service
            python-version: "3.10"
          - dir: user-service
            python-version: "3.10"
          - dir: tutor-service
            python-version: "3.10"
          - dir: material-service
            python-version: "3.10"
          - dir: info-service
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ matrix.dir }}

      - name: Create env
        run: echo "DJANGO_KEY=${{ secrets.DJANGO_KEY }}" >> .env
        working-directory: ${{ matrix.dir }}

      - name: Run Tests
        run: python manage.py test --settings=NoteAlly.test_settings --noinput
        working-directory: ${{ matrix.dir }}